"""Pydantic models for structured peer review with confidence scoring."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# ---------------------------------------------------------------------------
# Per-criterion and per-section scoring models
# ---------------------------------------------------------------------------


@dataclass
class ReviewCriterion:
    """A single evaluation criterion within a review section."""
    name: str
    score: float  # 0.0 - 1.0
    justification: str


@dataclass
class ReviewSection:
    """Evaluation of a single paper section (e.g. abstract, introduction, methodology)."""
    section_name: str
    overall_score: float  # 0.0 - 1.0
    criteria: list[ReviewCriterion] = field(default_factory=list)
    strengths: list[str] = field(default_factory=list)
    weaknesses: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Persona definitions
# ---------------------------------------------------------------------------


@dataclass
class PersonaDefinition:
    """Defines a reviewer persona with name, focus areas, and a detailed rubric."""
    name: str
    short_label: str
    focus_areas: list[str]
    rubric_description: str
    emphasis_weights: dict[str, float] = field(default_factory=dict)
    # temperature for LLM generation — lower for stricter, higher for creative
    temperature: float = 0.3


# ---------------------------------------------------------------------------
# Full review output from one persona
# ---------------------------------------------------------------------------


@dataclass
class PersonaReview:
    """Complete structured review generated by a single persona."""
    persona: str
    persona_label: str
    overall_score: float  # 0.0 - 1.0
    overall_confidence: float  # 0.0 - 1.0
    sections: list[ReviewSection] = field(default_factory=list)
    strengths: list[str] = field(default_factory=list)
    weaknesses: list[str] = field(default_factory=list)
    questions: list[str] = field(default_factory=list)
    recommendation: str = ""  # accept / minor-revision / major-revision / reject
    raw_text: str = ""  # Full markdown review report for export


# ---------------------------------------------------------------------------
# Aggregated meta-review
# ---------------------------------------------------------------------------


@dataclass
class MetaReview:
    """Aggregated review combining multiple persona reviews into a meta-review."""
    persona_count: int
    overall_score: float  # Average across personas
    overall_confidence: float  # Weighted average
    aggregated_strengths: list[str] = field(default_factory=list)
    aggregated_weaknesses: list[str] = field(default_factory=list)
    consensus_questions: list[str] = field(default_factory=list)
    score_variance: float = 0.0  # Variance across persona scores
    per_persona_scores: dict[str, float] = field(default_factory=dict)
    per_persona_confidence: dict[str, float] = field(default_factory=dict)
    consensus_recommendation: str = ""  # Meta recommendation
    meta_review_text: str = ""  # Human-readable meta-review summary
    disagreement_areas: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Conversion helpers
# ---------------------------------------------------------------------------


def persona_review_to_dict(review: PersonaReview) -> dict[str, Any]:
    """Convert a PersonaReview to a JSON-serializable dict."""
    return {
        "persona": review.persona,
        "persona_label": review.persona_label,
        "overall_score": review.overall_score,
        "overall_confidence": review.overall_confidence,
        "sections": [
            {
                "section_name": s.section_name,
                "overall_score": s.overall_score,
                "criteria": [
                    {"name": c.name, "score": c.score, "justification": c.justification}
                    for c in s.criteria
                ],
                "strengths": s.strengths,
                "weaknesses": s.weaknesses,
                "suggestions": s.suggestions,
            }
            for s in review.sections
        ],
        "strengths": review.strengths,
        "weaknesses": review.weaknesses,
        "questions": review.questions,
        "recommendation": review.recommendation,
        "raw_text": review.raw_text,
    }


def meta_review_to_dict(meta: MetaReview) -> dict[str, Any]:
    """Convert a MetaReview to a JSON-serializable dict."""
    return {
        "persona_count": meta.persona_count,
        "overall_score": meta.overall_score,
        "overall_confidence": meta.overall_confidence,
        "aggregated_strengths": meta.aggregated_strengths,
        "aggregated_weaknesses": meta.aggregated_weaknesses,
        "consensus_questions": meta.consensus_questions,
        "score_variance": meta.score_variance,
        "per_persona_scores": meta.per_persona_scores,
        "per_persona_confidence": meta.per_persona_confidence,
        "consensus_recommendation": meta.consensus_recommendation,
        "meta_review_text": meta.meta_review_text,
        "disagreement_areas": meta.disagreement_areas,
    }
