from __future__ import annotations

import re
from typing import Any


def extract_sections_from_latex(tex_content: str) -> dict[str, str]:
    sections: dict[str, str] = {}

    abstract_match = re.search(
        r"\\begin\{abstract\}(.*?)\\end\{abstract\}",
        tex_content, re.DOTALL
    )
    if abstract_match:
        sections["abstract"] = abstract_match.group(1).strip()

    title_match = re.search(r"\\title\{(.*?)\}", tex_content, re.DOTALL)
    if title_match:
        sections["title"] = title_match.group(1).strip()

    section_matches = re.finditer(
        r"\\section\{(.*?)\}(.*?)(?=\\section\{|\\bibliography|\\end\{document\}|\Z)",
        tex_content, re.DOTALL
    )
    for match in section_matches:
        heading = match.group(1).strip().lower()
        body = match.group(2).strip()
        sections[heading] = body

    return sections


SECTION_HEADING_OVERRIDES: dict[str, str] = {
    "introduction": "## Introduction",
    "methodology": "## How It Works",
    "results": "## Key Results",
    "conclusion": "## Conclusion",
    "related work": "## Related Work",
    "background": "## Background",
    "discussion": "## Discussion",
    "experiments": "## Experiments",
}


def generate_blog_post(sections: dict[str, str], topic: str) -> str:
    title = sections.get("title", topic)
    abstract = sections.get("abstract", "")
    body_md = f"""# {title}

## TL;DR
{abstract}

"""
    for key, body in sections.items():
        if key in ("title", "abstract"):
            continue
        heading = SECTION_HEADING_OVERRIDES.get(key, f"## {key.title()}")
        body_md += f"{heading}\n\n{body}\n\n"

    body_md += "---\n*Generated by Research Agent*\n"
    return body_md


def generate_newsletter(sections: dict[str, str]) -> str:
    abstract = sections.get("abstract", "")
    results = sections.get("results", "")
    summary = abstract[:200] + "..." if len(abstract) > 200 else abstract
    result_summary = results[:200] + "..." if len(results) > 200 else results
    return f"""**In Brief**

{summary}

**Key Finding**

{result_summary}

---"""


def generate_twitter_thread(sections: dict[str, str], paper_url: str = "") -> list[str]:
    title = sections.get("title", "New Paper")
    abstract = sections.get("abstract", "")
    results = sections.get("results", "")

    tweets = [
        f"New Paper: {title}",
        f"Abstract: {abstract[:240]}",
    ]
    if results:
        tweets.append(f"Key result: {results[:240]}")
    if paper_url:
        tweets.append(f"Read the full paper: {paper_url}")
    else:
        tweets.append("Read the full paper: [link]")
    return tweets


def generate_all(
    tex_content: str,
    topic: str,
    formats: list[str] | None = None
) -> dict[str, Any]:
    if formats is None:
        formats = ["blog", "newsletter", "twitter"]
    sections = extract_sections_from_latex(tex_content)
    output: dict[str, Any] = {}
    if "blog" in formats:
        output["blog"] = generate_blog_post(sections, topic)
    if "newsletter" in formats:
        output["newsletter"] = generate_newsletter(sections)
    if "twitter" in formats:
        output["twitter"] = generate_twitter_thread(sections)
    return output
